Repository tmenier/Flurl, pull requests merged in 2018-07, with the labels that each got.

#325 HttpTest use AsyncLocal like NetStandard in NetFramework 4.6 and later
  src/Flurl.Http/Flurl.Http.csproj
  src/Flurl.Http/Testing/HttpTest.cs
Labels: enhancement, in progress

#343 Flurl.Http 2.3.2
  Test/Flurl.Test/Http/FlurlClientTests.cs
  Test/Flurl.Test/Http/GetTests.cs
  Test/Flurl.Test/Http/RealHttpTests.cs
  Test/Flurl.Test/Http/TestingTests.cs
  src/Flurl.Http.CodeGen/Flurl.Http.CodeGen.csproj
  src/Flurl.Http.CodeGen/HttpExtensionMethod.cs
  src/Flurl.Http.CodeGen/Program.cs
  src/Flurl.Http/Flurl.Http.csproj
  src/Flurl.Http/FlurlClient.cs
  src/Flurl.Http/FlurlRequest.cs
  src/Flurl.Http/GeneratedExtensions.cs
  src/Flurl.Http/HttpMessage.cs
  src/Flurl.Http/HttpRequestMessageExtensions.cs
  src/Flurl.Http/HttpResponseMessageExtensions.cs
  src/Flurl.Http/Testing/FakeHttpMessageHandler.cs
  src/Flurl.Http/Testing/HttpCallAssertion.cs
  src/Flurl.Http/Testing/HttpTest.cs
  src/Flurl/Flurl.csproj
Labels: in progress

#344 Add implicit conversion from Flurl.Url to System.Uri.
  Test/Flurl.Test/UrlBuilderTests.cs
  src/Flurl.Http/Configuration/PerHostFlurlClientFactory.cs
  src/Flurl.Http/FlurlRequest.cs
  src/Flurl/Url.cs
Labels: next up

#350 Flurl 2.8
  Test/Flurl.Test/UrlBuilderTests.cs
  src/Flurl.Http/Configuration/PerHostFlurlClientFactory.cs
  src/Flurl.Http/FlurlRequest.cs
  src/Flurl/Flurl.csproj
  src/Flurl/Url.cs
Labels: in progress
